create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer, id integer not null auto_increment, salary integer not null, primary key (id)) engine=InnoDB;
alter table employee_salary add constraint UK_j083osjmuajoy4gwpwhj3e8nt unique (employee_id);
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer, id integer not null auto_increment, salary integer not null, primary key (id)) engine=InnoDB;
alter table employee_salary add constraint UK_j083osjmuajoy4gwpwhj3e8nt unique (employee_id);
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer, id integer not null auto_increment, salary integer not null, primary key (id)) engine=InnoDB;
alter table employee_salary add constraint UK_j083osjmuajoy4gwpwhj3e8nt unique (employee_id);
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer, id integer not null auto_increment, salary integer not null, primary key (id)) engine=InnoDB;
alter table employee_salary add constraint UK_j083osjmuajoy4gwpwhj3e8nt unique (employee_id);
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer, id integer not null auto_increment, salary integer not null, primary key (id)) engine=InnoDB;
alter table employee_salary add constraint UK_j083osjmuajoy4gwpwhj3e8nt unique (employee_id);
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer, id integer not null auto_increment, salary integer not null, primary key (id)) engine=InnoDB;
alter table employee_salary add constraint UK_j083osjmuajoy4gwpwhj3e8nt unique (employee_id);
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer, id integer not null auto_increment, salary integer not null, primary key (id)) engine=InnoDB;
alter table employee_salary add constraint UK_j083osjmuajoy4gwpwhj3e8nt unique (employee_id);
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer, id integer not null auto_increment, salary integer not null, primary key (id)) engine=InnoDB;
alter table employee_salary add constraint UK_j083osjmuajoy4gwpwhj3e8nt unique (employee_id);
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer, id integer not null auto_increment, salary integer not null, primary key (id)) engine=InnoDB;
alter table employee_salary add constraint UK_j083osjmuajoy4gwpwhj3e8nt unique (employee_id);
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer, id integer not null auto_increment, salary integer not null, primary key (id)) engine=InnoDB;
alter table employee_salary add constraint UK_j083osjmuajoy4gwpwhj3e8nt unique (employee_id);
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
create table employee (id integer not null auto_increment, email varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table employee_salary (employee_id integer not null, salary integer not null, primary key (employee_id)) engine=InnoDB;
alter table employee_salary add constraint FKo7mki93c83b1kx9olp1vmcwcq foreign key (employee_id) references employee (id);
